FROM nginx:1.27.4

# คัดลอกไฟล์คอนฟิกหลัก
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# คัดลอกไฟล์คอนฟิกของ virtual hosts
COPY nginx/conf.d/ /etc/nginx/conf.d/

# HTML custom error
COPY nginx/nginx_static /usr/share/nginx/html/