services:
  mongodb:
    build:
      context: .
      dockerfile: dockerfile.mongo
    container_name: "${MONGO_CONTAINER_NAME}"
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - "${MONGO_PATH}:/data/db"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
  nginx:
    build:
      context: .
      dockerfile: dockerfile.nginx
    container_name: "nginx"
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - "${NGINX_VOLUMES}:/var/www/data"
      - "${NGINX_VOLUMES}${NGINX_VOLUMES_LOG}:/var/log/nginx"
      - "${NGINX_VOLUMES}${NGINX_VOLUMES_UPLOAD}:/var/www/data/upload"
  # spring-boot:
  #   build:
  #     context: .
  #     dockerfile: dockerfile.spring.boot
  #   container_name: spring-boot
  #   depends_on:
  #     - mongodb
  #     - nginx
  #   ports:
  #     - "${UAT_SPRING_BOOT_PORT}:${UAT_SPRING_BOOT_PORT}"
  #   env_file:
  #     - .env
